#!/bin/bash

maxMsgLength=122

a=$(echo $(cat "$1"))
n=${#a}

if [[ $n -gt $maxMsgLength ]]; then
    echo -e "[commit-msg-hook] Your commit message exceeds the max characters length of $maxMsgLength.\nPlease review the commit message.\nMsg: $n" >&2
	exit 1
fi

REGEX_ISSUE_ID="^(fix|feat|docs|test|chore|ci|perf|style|build|refactor)(?:(\()([a-zA-Z]+)(\)))?:(?:(\s#[0-9]+))?(\s[A-zÀ-ÿ])([A-zÀ-ÿ0-9\s:-?#$&\(-\/]+)$"

if ! grep -qP "$REGEX_ISSUE_ID" "$1"; then
    echo -e "[commit-msg-hook] Your commit message is illegal.\nPlease rename your message using following regex: $REGEX_ISSUE_ID" >&2
    exit 1
fi