#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.ts\{0,1\}$")

FILE_PATH="$(dirname "$(realpath $0)")"

if [[ "$STAGED_FILES" = "" ]]; then
	printf "No files to review\n"
	exit 0
fi

PASS=true
EXIT=0

printf "Validating Javascript:\n"

# Check for eslint
FILE_ESLINT="$FILE_PATH/../node_modules/eslint/bin/eslint.js"
if [ ! -f "$FILE_ESLINT" ]; then
	printf "Please install ESlint\n"
	exit 1
fi

for FILE in $STAGED_FILES
do
  FILE_HELP="$FILE_PATH/../../$FILE"

  if grep -q "it.only(" "$FILE_HELP" || grep -q "describe.only(" "$FILE_HELP"; then
    printf "Remove the only from the test file $FILE."
	PASS=false
	EXIT=1
  fi

  yarn run eslint "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "ESLint Passed: $FILE\n"
  else
    printf "ESLint Failed: $FILE\n"
    PASS=false
	EXIT=1
  fi
done

printf "\nJavascript validation completed!\n"

if ! $PASS; then
  printf "COMMIT FAILED: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n"
fi

exit $EXIT